### Get all dogs (encontrados)
GET http://localhost:3000/api/dogs?status=encontrado HTTP/1.1

### Get all dogs (perdidos)
GET http://localhost:3000/api/dogs?status=perdido HTTP/1.1

### Get dog by ID
GET http://localhost:3000/api/dogs/62f2c41a2b8695489595f3cb HTTP/1.1

### Update dog
PUT http://localhost:3000/api/dogs/62f2c41a2b8695489595f3cb HTTP/1.1
Content-Type: application/json
Authorization: Bearer v4.public.eyJzdWIiOiI2MmU1NDJjM2YyM2FiYWZkN2FmMTZlYTkiLCJpYXQiOiIyMDIyLTA4LTA5VDE5OjU2OjIzLjE5OVoiLCJleHAiOiIyMDIyLTA4LTE1VDE5OjU2OjIzLjE5OVoifZMqT1_NcSR-QNcgVoES65KYUBqEeyIDPytKcenTctRVUy7Rbcb0cyh6jGGB0TtiszEXln62SWqDCopvt4OJCQQ

{
  "status": "resuelto"
}


### Post a new dog
POST http://localhost:3000/api/dogs/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer v4.public.eyJzdWIiOiI2MmU1NDJjM2YyM2FiYWZkN2FmMTZlYTkiLCJpYXQiOiIyMDIyLTA4LTA5VDE5OjU2OjIzLjE5OVoiLCJleHAiOiIyMDIyLTA4LTE1VDE5OjU2OjIzLjE5OVoifZMqT1_NcSR-QNcgVoES65KYUBqEeyIDPytKcenTctRVUy7Rbcb0cyh6jGGB0TtiszEXln62SWqDCopvt4OJCQQ

{
  "name": "Api",
  "date": 20220801,
  "color": ["chocolate"],
  "location": "San Cristobal",
  "status": "perdido",
  "breed": "labrador",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor"
}

### Delete a dog
DELETE http://localhost:3000/api/dogs/62f2bbfd7912ccce38e76390 HTTP/1.1
Authorization: Bearer v4.public.eyJzdWIiOiI2MmU1NDJjM2YyM2FiYWZkN2FmMTZlYTkiLCJpYXQiOiIyMDIyLTA4LTA5VDE5OjU2OjIzLjE5OVoiLCJleHAiOiIyMDIyLTA4LTE1VDE5OjU2OjIzLjE5OVoifZMqT1_NcSR-QNcgVoES65KYUBqEeyIDPytKcenTctRVUy7Rbcb0cyh6jGGB0TtiszEXln62SWqDCopvt4OJCQQ

### All dogs by creator
GET http://localhost:3000/api/dogs/mine HTTP/1.1
Authorization: Bearer v4.public.eyJzdWIiOiI2MmU1NDJjM2YyM2FiYWZkN2FmMTZlYTkiLCJpYXQiOiIyMDIyLTA4LTA5VDE5OjU2OjIzLjE5OVoiLCJleHAiOiIyMDIyLTA4LTE1VDE5OjU2OjIzLjE5OVoifZMqT1_NcSR-QNcgVoES65KYUBqEeyIDPytKcenTctRVUy7Rbcb0cyh6jGGB0TtiszEXln62SWqDCopvt4OJCQQ

### Dogs with filters
GET http://localhost:3000/api/dogs/find?status=encontrado&color=Negro&from=20220809&location=crespo HTTP/1.1

### User Sign Up
POST http://localhost:3000/api/user/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Elliot",
  "email": "e@rob.ot",
  "pass": "mr_robot_404"
}

### User Sign In
POST http://localhost:3000/api/user/signin HTTP/1.1
Content-Type: application/json

{
  "email": "german@rob.ot",
  "pass": "mr_robot_403"
}

### User Me
GET http://localhost:3000/api/user/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer v4.public.eyJzdWIiOiI2MmUyZjg2ZWNhYzg0M2UzMzBjMDBmNDgiLCJpYXQiOiIyMDIyLTA3LTI4VDIwOjU5OjAwLjM5OFoiLCJleHAiOiIyMDIyLTA4LTA0VDIwOjU5OjAwLjM5OFoifUI_gT2XXoOwDcsLGJtG5CSFZGJW3qCV9lfRDQMq2AahI6KMONQE3_xn1HV2Xvtl5Rp5m6twQfyX6bxLMcupYg0

### User contact details
GET http://localhost:3000/api/user/contact?id=62e542c3f23abafd7af16ea9 HTTP/1.1
Authorization: Bearer v4.public.eyJzdWIiOiI2MmU1NDJjM2YyM2FiYWZkN2FmMTZlYTkiLCJpYXQiOiIyMDIyLTA4LTA5VDE5OjU2OjIzLjE5OVoiLCJleHAiOiIyMDIyLTA4LTE1VDE5OjU2OjIzLjE5OVoifZMqT1_NcSR-QNcgVoES65KYUBqEeyIDPytKcenTctRVUy7Rbcb0cyh6jGGB0TtiszEXln62SWqDCopvt4OJCQQ

